### ISSUE TITLE
Add to Google Fonts

### ISSUE THREAD

**Issue by cmahnke** [Gissio/font_tiny5#1]
See https://github.com/google/fonts/issues/new/choose

Adding to https://fontsource.org/ would be also nice, since this would imply a NPM distribution, but I'm not sure how to add there...

**Comment by Gissio** [comment]
Feel free to post your comments here [https://github.com/google/fonts/issues/7149](https://github.com/google/fonts/issues/7149)!

I didn't know about fontsource.org, thanks for sharing.

**Comment by cmahnke** [comment]
The [Fontsource repo](https://github.com/fontsource/font-files) is also on GitHub. Since it includes the Google Fonts, I suspect getting it in there would be enough, it will certainly get picked up by Fontsource later on.

Thanks!

**Comment by cmahnke** [comment]
Great!
Now also here https://fontsource.org/fonts/tiny5
